//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTMO.Text.FileGenerator.Provider.DSC.LoggingMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UTMO.Text.FileGenerator.Provider.DSC.LoggingMessages.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered Unhandled Exception Fetching a property from the property bag. Exception Message: {ExceptionMessage}.
        /// </summary>
        internal static string DscPropertyBagUnhandledException {
            get {
                return ResourceManager.GetString("DscPropertyBagUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an error while trying to produce the output path for {ResourceName}.
        /// </summary>
        internal static string ErrorGeneratingMofOutputPath {
            get {
                return ResourceManager.GetString("ErrorGeneratingMofOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an error while trying to produce the output path for {ResourceName}.
        /// </summary>
        internal static string ErrorGeneratingOutputPath {
            get {
                return ResourceManager.GetString("ErrorGeneratingOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an exception of type {ExceptionType} while trying to generate the MOF file for {ResourceName}.
        ///Error Stream: {StandardError}.
        /// </summary>
        internal static string MofGenerationException {
            get {
                return ResourceManager.GetString("MofGenerationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an error while trying to generate the MOF file for {ResourceName}.
        ///Error Stream: {StandardError}.
        /// </summary>
        internal static string MofGenerationFailed {
            get {
                return ResourceManager.GetString("MofGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MOFGEN] StdOut: {StandardOutput}.
        /// </summary>
        internal static string MofGenerationStdOut {
            get {
                return ResourceManager.GetString("MofGenerationStdOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully generated the MOF file for {ResourceName}.
        /// </summary>
        internal static string MofGenerationSucceeded {
            get {
                return ResourceManager.GetString("MofGenerationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOF Output Path: {mofOutputFile}.
        /// </summary>
        internal static string MofOutputPath {
            get {
                return ResourceManager.GetString("MofOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully restore required modules..
        /// </summary>
        internal static string RestoredRequiredModulesSucceeded {
            get {
                return ResourceManager.GetString("RestoredRequiredModulesSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [RestoreModules] STD Out: {stdOut}.
        /// </summary>
        internal static string RestoreModulesStdOut {
            get {
                return ResourceManager.GetString("RestoreModulesStdOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an error restoring required modules. Std Err:  {stdErr}.
        /// </summary>
        internal static string RestoreRequiredModulesFailed {
            get {
                return ResourceManager.GetString("RestoreRequiredModulesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Config Path: {scriptConfig}.
        /// </summary>
        internal static string ScriptConfigPath {
            get {
                return ResourceManager.GetString("ScriptConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping &quot;{ResourceName}&quot; as it is not a DSC Configuration or LCM Configuration.
        /// </summary>
        internal static string SkippingNonDscResource {
            get {
                return ResourceManager.GetString("SkippingNonDscResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning generate MOF file for &quot;{ResourceName}&quot;.
        /// </summary>
        internal static string StartingMofFileGeneration {
            get {
                return ResourceManager.GetString("StartingMofFileGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning Restore Required Modules Plugin..
        /// </summary>
        internal static string StartingRestoreRequiredModules {
            get {
                return ResourceManager.GetString("StartingRestoreRequiredModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing the Restore Required Modules to Disk.
        /// </summary>
        internal static string WritingRestoreRequiredModules {
            get {
                return ResourceManager.GetString("WritingRestoreRequiredModules", resourceCulture);
            }
        }
    }
}
