name: ${{ parameters.MajorVersion }}.${{ parameters.MinorVersion }}$(Rev:.r)

parameters:
  - name: Configuration
    type: string
    default: Release
    values:
      - Release
      - Debug
  - name: MajorVersion
    type: string
    default: 3
  - name: MinorVersion
    type: string
    default: 2

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - src/UTMO.Text.FileGenerator.Provider.DSC/*
      - src/UTMO.Text.FileGenerator.Provider.DSC.*/*

resources:
  repositories:
    - repository: Templates
      type: git
      name: OneBuild\OneBuild.Pipelines.v2
      ref: refs/heads/main
      endpoint: UTMO

variables:
  - name: ProjectRoot
    value: $(Build.SourcesDirectory)/src
  - name: Projects
    value: '$(ProjectRoot)/**/*.sln'

extends:
  template: v2/Pipelines/UserTemplates/Unified/BuildDeploy.NugetPkg.Template.yml@Templates
  parameters:
    BuildPool: Public
    NugetConfigPath: $(RepoRoot)/src/nuget.config
    ProjectsToBuild: $(Projects)
    ProjectsToRestore: $(Projects)
    DotNetVersion: '9.0.x'
    DeploymentName: DSCGenerator
    ReleaseDisplayName: 'Publish DSC Generator Packages'
    UseWildcardMatch: true
    FeedSettings:
      'ConfigGen': 'internal'
      'UTMO Packages': 'external'